monitor = ""
as_window = false
timeout = 0
disable_click_to_close = false
force_keyboard_focus = false

[list]
keyboard_scroll_style = "vim"
max_entries = 50
show_initial_entries = true
single_click = true
visibility_threshold = 20
placeholder = "No Results"

[keybinds]
next = ["ctrl n", "Down"]
previous = ["ctrl p", "Up"]
quick_activate = []

[providers]
default = ["desktopapplications", "calc", "runner", "websearch", "menus", "pw"]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "!"
provider = "todo"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[[providers.prefixes]]
prefix = "pw "
provider = "pw"

[providers.actions]
fallback = [
	{ action = "menus:open", label = "open", after = "Nothing" },
	{ action = "erase_history", label = "clear hist", bind = "ctrl h", after = "AsyncReload" },
]
desktopapplications = [
	{ action = "start", default = true, bind = "Return" },
	{ action = "start:keep", label = "open+next", bind = "shift Return", after = "KeepOpen" },
	{ action = "erase_history", label = "clear hist", bind = "ctrl h", after = "AsyncReload" },
	{ action = "pin", bind = "ctrl alt p", after = "Nothing" },
	{ action = "unpin", bind = "ctrl alt p", after = "Nothing" },
	{ action = "pinup", bind = "ctrl alt n", after = "Nothing" },
	{ action = "pindown", bind = "ctrl alt m", after = "Nothing" },
]
