clone_repo_switch = "Always"
full_path = true
display_full_path = true

[[search_dirs]]
path = "/home/quirinecker/projects"
depth = 10

[[search_dirs]]
path = "/home/quirinecker/.config"
depth = 10

[[search_dirs]]
path = "/home/quirinecker/tmp/projects/"
depth = 10

[[search_dirs]]
path = "/home/quirinecker/Nextcloud/obsidian"
depth = 1
